[tool.poetry]
name = "flaskminiproject"
version = "0.1.0"
description = ""
authors = ["Umdoong <umdoongs@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
flask = "^3.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
